### ISSUE TITLE
Unable to resolve module `../constants/html` from `Signalus/src/screens/ConsentHTMLScreen.js`

### ISSUE THREAD

**Issue by ravisojitra** [TaeJoongYoon/Signalus#3]
Can't run the application, Here's error log.

> bundling failed: Error: Unable to resolve module `../constants/html` from `/Users/apex-5/Desktop/ravi/react-native/Signalus/src/screens/ConsentHTMLScreen.js`: The module `../constants/html` could not be found from `/Users/apex-5/Desktop/ravi/react-native/Signalus/src/screens/ConsentHTMLScreen.js`. Indeed, none of these files exist:
> 
>   * `/Users/apex-5/Desktop/ravi/react-native/Signalus/src/constants/html(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json)`
>   * `/Users/apex-5/Desktop/ravi/react-native/Signalus/src/constants/html/index(.native||.ios.js|.native.js|.js|.ios.json|.native.json|.json)`
>     at ModuleResolver.resolveDependency (/Users/apex-5/Desktop/ravi/react-native/Signalus/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:167:697)
>     at ResolutionRequest.resolveDependency (/Users/apex-5/Desktop/ravi/react-native/Signalus/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:80:16)
>     at DependencyGraph.resolveDependency (/Users/apex-5/Desktop/ravi/react-native/Signalus/node_modules/metro/src/node-haste/DependencyGraph.js:237:485)
>     at Object.resolve (/Users/apex-5/Desktop/ravi/react-native/Signalus/node_modules/metro/src/lib/transformHelpers.js:116:25)
>     at dependencies.map.result (/Users/apex-5/Desktop/ravi/react-native/Signalus/node_modules/metro/src/DeltaBundler/traverseDependencies.js:298:29)
>     at Array.map (<anonymous>)
>     at resolveDependencies (/Users/apex-5/Desktop/ravi/react-native/Signalus/node_modules/metro/src/DeltaBundler/traverseDependencies.js:294:16)
>     at /Users/apex-5/Desktop/ravi/react-native/Signalus/node_modules/metro/src/DeltaBundler/traverseDependencies.js:159:33
>     at Generator.next (<anonymous>)
>     at step (/Users/apex-5/Desktop/ravi/react-native/Signalus/node_modules/metro/src/DeltaBundler/traverseDependencies.js:239:307)

**Comment by TaeJoongYoon** [comment]
The html files are private. So I didn't upload that files

**Comment by ravisojitra** [comment]
then how do i run the project

**Comment by TaeJoongYoon** [comment]
I'm sorry for late.

Um... I don't give you the files... so you should edit some code.
